### ISSUE TITLE
Incorrect user in the s3 policy for the 04_Cross-AccountPermissions demo setup

### ISSUE THREAD

**Issue by dbachan** [acantril/aws-sa-pro#15]
The user should be iamadmin instead of bob

**Comment by acantril** [comment]
?? i don't understand. Why should it be iamadmin ? we're using a iam identity called bob ?

**Comment by dbachan** [comment]
hmm... maybe I don't understand, but I thought that we're granting the access through the bucket policy for the identity iamadmin in the general account. The video also uses iamadmin user, see 2:09 of the [202205UPDATE] [DEMO] Cross Account Access to S3 - BUCKET POLICY - STAGE3 lesson

In the presentation it says bob, but in the video for the accounts setup it uses iamadmin.

**Comment by acantril** [comment]
So I'm a little confused here still
You are doing the lesson in the SA Pro course right ? the cross account demo.
So why are you using anything in the SA Pro repo ? the links for this specific lesson are attached to the lesson itself - there is a pair of download links and a 1 click deployment and all of these are showing iamadmin ?

The files in the SA Pro repo are for an older version of this demo, but that's not the one you are doing ? unless im missing something here.

**Comment by acantril** [comment]
These are what are attached to the lesson

[1-Click Deployment](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?templateURL=https://learn-cantrill-labs.s3.amazonaws.com/awscoursedemos/0039-aws-mixed-cross-account-s3/prod_bucketsandrole.yaml&stackName=buckets) - PRODUCTION ACCOUNT

[Bucket Images](https://learn-cantrill-labs.s3.amazonaws.com/awscoursedemos/0039-aws-mixed-cross-account-s3/bucket_images.zip)

[Bucket Policy](https://learn-cantrill-labs.s3.amazonaws.com/awscoursedemos/0039-aws-mixed-cross-account-s3/petpics_policy.json)

None of those mention bob ?

**Comment by dbachan** [comment]
Right, somehow when I got to this lesson I forgot about the bucket policy from the first one. Was looking for the link under this lesson, but couldn't find it, thus I opened the repo. Kind of liked the idea that everything is in one github repo instead of the lessons. Maybe these could be links to the GitHub files and then kept in synch?

Thank you for the guidance. I'll use the links from the videos. But having the opportunity wanted to thank you for the effort put into this course, it's great content!

**Comment by acantril** [comment]
Weirdly enough, I'm actually moving away from repos for code/assets - there have been so many people who just find it a friction point. That's why i moved to 1 clicks and downloadable assets. I may just set up something automated to keep the course repos updated as well for those who want that.

Thanks for the feedback though anyway, it's the only way i get to sanity check things. Glad you're enjoying it :)
