### ISSUE TITLE
Issue with bob password AllowedPattern

### ISSUE THREAD

**Issue by ghostcodekc** [acantril/aws-sa-pro#3]
Is there any reason why the following was chosen in the file aws-sa-pro/03-AdvancedPermissionsAndAccounts/04_Cross-AccountPermissions/01_DEMOSETUP/bob.yaml :  

`AllowedPattern: ^[a-zA-Z0-9]*$`

I came across an issue when using a randomly generated password that included a special character "@" or "!" as it did not conform to the password pattern.

**Comment by acantril** [comment]
it's a standard thats part of a lot of AWS templates ... lowest common denominator
