### ISSUE TITLE
Error while uploading the file

### ISSUE THREAD

**Issue by MohamedAYACH** [acantril/aws-sa-pro#7]
Hi,

I get this error when trying to upload please help:
The following resource types are not supported for resource import: AWS::SSM::Parameter,AWS::EC2::VPCCidrBlock,AWS::EC2::VPCGatewayAttachment,AWS::EC2::SecurityGroupIngress,AWS::EC2::Route,AWS::EC2::Route,AWS::EC2::SubnetRouteTableAssociation,Custom::SubnetModify,Custom::SubnetModify,AWS::EC2::SubnetRouteTableAssociation,AWS::EC2::SubnetRouteTableAssociation,Custom::SubnetModify

**Comment by acantril** [comment]
you shouldn't be importing resources at any point. I suspect you have selected the wrong option when creating the cloud formation stack. Import rather than new resources.
